language: node_js

node_js: '10'

cache: npm

install:
  - npm install -g codecov
  - npm install

script:
  - npm run test:unit
  - npm run mb:start &
  - npm run test:e2e:ci
  - npm run build

after_success:
  - codecov
