language: node_js

node_js: '10'

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm install -g codecov
  - npm install

script:
  - npm run test:unit
  - npm run test:mut
  - npm run test:e2e:ci
  - npm run build

after_success:
  - codecov
